spring:
    devtools:
       restart:
          trigger-file: trigger.txt
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://127.0.0.1:3306/g7?useSSL=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
    redis:
      open: true  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 6000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
    activemq:
      user: admin #用户名
      password: admin #密码
      broker-url: tcp://127.0.0.1:61616 #连接地址
      packages:
        trust-all: true #开放所有包限制
      pool: #连接池
        max-connections: 1500    #最大连接数
        idle-timeout: 3000
        time-between-expiration-check: 3000
        max-active-session-per-connection: 50
# 设置SwaggerUI的在线文档是否开启                       
swagger: 
  show: true